<?php

namespace app\controllers;

use Yii;
use app\models\Menu;
use yii\web\NotFoundHttpException;
class MenuController extends BaseController
{   
    
    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index'],$action['create'],$action['update'],$action['view'],$action['delete']);
        return $action;
    }
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {   
        return Menu::list(Yii::$app->request->queryParams);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionCreate()
    {

        $model = new Menu();
        $post = Yii::$app->request->post();
        $data = ['Menu'=>$post];
        $model->load($data);
        $model->created_at = date('Y-m-d H:i:s',time());
        $model->deleted_at = 0;
        if ($model->save()) {
            $this->trigger(self::EVENT_SAVE_LOG,new \yii\base\Event(['sender'=>'新增菜单'.$post['name']]));
            return $this->response->data = ['status'=>200,'msg'=>'添加成功'];
        }
        return $this->response->data = ['msg'=>'添加失败','error'=>404];
    }

     public function actionUpdate($id)
    {

        $model = $this->findModel($id);
        $post = Yii::$app->request->post();
        $post['pid'] = (string)$post['pid'];
        $data = ['Menu'=>$post];
        $model->load($data);
        
        if ($model->save()) {
            $this->trigger(self::EVENT_SAVE_LOG,new \yii\base\Event(['sender'=>'修改菜单id'.((array)($model->_id))['oid'].'为'.$post['name']]));
            return $this->response->data = ['status'=>200,'msg'=>'修改成功'];
        }
        return $this->response->data = ['msg'=>'修改失败','status'=>404];
    }
    
  
    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionView($id)
    {
        return $this->findModel($id);
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted_at = time();

        $model->save();
        $this->trigger(self::EVENT_SAVE_LOG,new \yii\base\Event(['sender'=>'删除菜单'.$model['name']]));
        return $this->response->data = ['msg'=>'删除成功','status'=>200];
    }

    public function actionLevelmenu(){
        $res=Menu::find()->asArray()->all();
        return array_merge([['title'=>'顶级','children'=>[],'key'=>'0','value'=>'0']],Menu::listRole($res));
    }
    /**
     * Displays about page.
     *
     * @return string
     */
    protected function findModel($id)
    {
        if (($model = Menu::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}
