<?php

namespace app\controllers;

use Yii;
use app\models\Role;
use yii\web\NotFoundHttpException;
class RoleController extends BaseController
{   
    
    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index'],$action['create'],$action['update'],$action['view'],$action['delete']);
        return $action;
    }
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {   
        return Role::list(Yii::$app->request->queryParams);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionCreate()
    {

        $model = new Role();
        $data = ['Role'=>Yii::$app->request->post()];
        $model->load($data);
        $model->created_at = date('Y-m-d H:i:s',time());
        $model->deleted_at = 0;
        if ($model->save()) {
            $this->trigger(self::EVENT_SAVE_LOG,new \yii\base\Event(['sender'=>'新增角色'.$model->name]));
            return $this->response->data = ['status'=>200,'msg'=>'添加成功'];
        }
        return $this->response->data = ['msg'=>'添加失败','status'=>404];
    }

     public function actionUpdate($id)
    {

        $model = $this->findModel($id);
        $post = Yii::$app->request->post();
        if(isset($post['menu_ids'])){
            $post['menu_ids'] = implode(',', $post['menu_ids']);
        }
        $data = ['Role'=>$post];
        $model->load($data);
        
        if ($model->save()) {
            $this->trigger(self::EVENT_SAVE_LOG,new \yii\base\Event(['sender'=>'修改角色id'.((array)($model->_id))['oid'].'为'.$model->name]));
            return $this->response->data = ['status'=>200,'msg'=>'修改成功'];
        }
        return $this->response->data = ['msg'=>'修改失败','status'=>404];
    }
    
  
    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionView($id)
    {
        $data = $this->findModel($id);
        $data['menu_ids'] = explode(',', $data['menu_ids']);
        return $data;
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted_at = time();

        $model->save();
        $this->trigger(self::EVENT_SAVE_LOG,new \yii\base\Event(['sender'=>'删除角色'.$model->name]));
        return $this->response->data = ['msg'=>'删除成功','status'=>200];
    }
    /**
     * Displays about page.
     *
     * @return string
     */
    protected function findModel($id)
    {
        if (($model = Role::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}
