<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\web\NotFoundHttpException;
use app\models\LoginForm;
class UserController extends BaseController
{   
    

    
    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index'],$action['create'],$action['update'],$action['view'],$action['delete']);
        return $action;
    }
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {   
        $user = User::list(Yii::$app->request->queryParams);
        return $user;
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionCreate()
    {

        $model = new User();
        $post = Yii::$app->request->post();
        $post['role_id'] = (string)$post['role_id'];
        $data = ['User'=>$post];
        $model->load($data);
        $model->salt = \Yii::$app->getSecurity()->generateRandomString();
        $model->password = \Yii::$app->getSecurity()->generatePasswordHash($model->salt.$model->password);
        $model->created_at = date('Y-m-d H:i:s',time());
        $model->deleted_at = 0;
        if ($model->save()) {
            $this->trigger(self::EVENT_SAVE_LOG,new \yii\base\Event(['sender'=>'新增用户id'.((array)($model->_id))['oid'].$model->username]));
            return $this->response->data = ['id'=>((array)($model->_id))['oid'],'msg'=>'添加成功'];
        }
        return $this->response->data = ['msg'=>'添加失败','code'=>404];
    }

     public function actionUpdate($id)
    {

        $model = $this->findModel($id);
        $post = Yii::$app->request->post();
        $post['role_id'] = (string)$post['role_id'];
        $data = ['User'=>$post];
        
        $model->load($data);
        if(isset($post['password'])){
            $model->salt = \Yii::$app->getSecurity()->generateRandomString();
            $model->password = \Yii::$app->getSecurity()->generatePasswordHash($model->salt.$model->password); 
        }
        if ($model->save()) {
            $this->trigger(self::EVENT_SAVE_LOG,new \yii\base\Event(['sender'=>'修改用户id'.((array)($model->_id))['oid'].$model->username]));
            return $this->response->data = ['id'=>((array)($model->_id))['oid'],'msg'=>'修改成功'];
        }
        return $this->response->data = ['msg'=>'添加失败','status'=>400];
    }
    
    public function actionLogin()
    {
        $model = new LoginForm();
        
        if ($model->load(['LoginForm'=>Yii::$app->request->post()]) && $model->login()) { 
             \app\models\UserLog::saveLog(new \yii\base\Event(['sender'=>'登录']),$model->getuser());
            return $model->getUserToken();
        }
        
        return ['msg'=>'账号或密码错误','status'=>'fail','code'=>'401'];
    }
    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionView($id)
    {
        $model = User::find()->where(['_id'=>$id])->select(['username','status','created_at','remark','role_id'])->one();
        return $model;
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted_at = time();

        $model->save();
        return $this->response->data = ['msg'=>'删除成功','status'=>200];
    }
    /**
     * Displays about page.
     *
     * @return string
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
